import imgF1 from "../media/img/market/f1.png";
// t
import imgT1 from "../media/img/market/t1.png";
// c
import imgC1 from "../media/img/market/c1.png";
// e
import imgE1 from "../media/img/market/e1.png";

const products = [
  {
    id: 1,
    title: "Frame Title",
    type: "frame",
    category: "standart",
    picture: imgF1,
    price: 1.99,
  },
  {
    id: 2,
    title: "Frame Title",
    type: "frame",
    category: "standart",
    picture: imgF1,
    price: 1.99,
  },
  {
    id: 3,
    title: "Frame Title",
    type: "frame",
    category: "standart",
    picture: imgF1,
    price: 1.99,
  },
  {
    id: 4,
    title: "Frame Title",
    type: "frame",
    category: "standart",
    picture: imgF1,
    price: 1.99,
  },
  {
    id: 5,
    title: "Table Title",
    type: "table",
    category: "standart",
    picture: imgT1,
    price: 1.99,
  },
  {
    id: 6,
    title: "Table Title",
    type: "table",
    category: "standart",
    picture: imgT1,
    price: 1.99,
  },
  {
    id: 7,
    title: "Table Title",
    type: "table",
    category: "standart",
    picture: imgT1,
    price: 1.99,
  },
  {
    id: 8,
    title: "Table Title",
    type: "table",
    category: "standart",
    picture: imgT1,
    price: 1.99,
  },
  {
    id: 9,
    title: "Card Title",
    type: "card",
    category: "standart",
    picture: imgC1,
    price: 1.99,
  },
  {
    id: 10,
    title: "Card Title",
    type: "card",
    category: "standart",
    picture: imgC1,
    price: 1.99,
  },
  {
    id: 11,
    title: "Card Title",
    type: "card",
    category: "standart",
    picture: imgC1,
    price: 1.99,
  },
  {
    id: 12,
    title: "Card Title",
    type: "card",
    category: "standart",
    picture: imgC1,
    price: 1.99,
  },
  {
    id: 13,
    title: "Emoji Title",
    type: "emoji",
    category: "standart",
    picture: imgE1,
    price: 1.99,
  },
  {
    id: 14,
    title: "Emoji Title",
    type: "emoji",
    category: "standart",
    picture: imgE1,
    price: 1.99,
  },
  {
    id: 15,
    title: "Emoji Title",
    type: "emoji",
    category: "standart",
    picture: imgE1,
    price: 1.99,
  },
  {
    id: 16,
    title: "Emoji Title",
    type: "emoji",
    category: "standart",
    picture: imgE1,
    price: 1.99,
  },
  {
    id: 17,
    title: "Special Emoji",
    type: "emoji",
    category: "special",
    picture: imgE1,
    price: 2.99,
  },
  {
    id: 18,
    title: "Rare Emoji",
    type: "emoji",
    category: "rare",
    picture: imgE1,
    price: 3.99,
  },
  {
    id: 19,
    title: "Relic Emoji",
    type: "emoji",
    category: "relic",
    picture: imgE1,
    price: 4.99,
  },
  {
    id: 20,
    title: "Special Frame",
    type: "frame",
    category: "special",
    picture: imgF1,
    price: 2.99,
  },
  {
    id: 21,
    title: "Rare Frame",
    type: "frame",
    category: "rare",
    picture: imgF1,
    price: 3.99,
  },
  {
    id: 22,
    title: "Relic Frame",
    type: "frame",
    category: "relic",
    picture: imgF1,
    price: 4.99,
  },
  {
    id: 23,
    title: "Special Table",
    type: "table",
    category: "special",
    picture: imgT1,
    price: 2.99,
  },
  {
    id: 24,
    title: "Rare Table",
    type: "table",
    category: "rare",
    picture: imgT1,
    price: 3.99,
  },
  {
    id: 25,
    title: "Relic Table",
    type: "table",
    category: "relic",
    picture: imgT1,
    price: 4.99,
  },
  {
    id: 26,
    title: "Special Card",
    type: "card",
    category: "special",
    picture: imgC1,
    price: 2.99,
  },
  {
    id: 24,
    title: "Rare Card",
    type: "card",
    category: "rare",
    picture: imgC1,
    price: 3.99,
  },
  {
    id: 25,
    title: "Relic Card",
    type: "card",
    category: "relic",
    picture: imgC1,
    price: 4.99,
  },
];

export default products;
