const rArr = [
  {
    id: 1,
    price: null,
    currency: null,
    owner_name: "Christian Bale",
    players_count: 2,
    players_limit: 3,
    status: "open",
  },
  {
    id: 2,
    price: null,
    currency: null,
    owner_name: "Christian Bale",
    players_count: 2,
    players_limit: 3,
    status: "open",
  },
  {
    id: 3,
    price: 5,
    currency: "DUR",
    owner_name: "Christian Bale",
    players_count: 2,
    players_limit: 3,
    status: "open",
  },
  {
    id: 4,
    price: null,
    currency: null,
    owner_name: "Christian Bale",
    players_count: 2,
    players_limit: 3,
    status: "open",
  },
  {
    id: 5,
    price: 10,
    currency: "DUR",
    owner_name: "Christian Bale",
    players_count: 1,
    players_limit: 2,
    status: "open",
  },
  {
    id: 6,
    price: 2,
    currency: "TON",
    owner_name: "Christian Bale",
    players_count: 2,
    players_limit: 3,
    status: "open",
  },
  {
    id: 7,
    price: null,
    currency: null,
    owner_name: "Christian Bale",
    players_count: 2,
    players_limit: 2,
    status: "open",
  },
  {
    id: 8,
    price: 1,
    currency: "PRM",
    owner_name: "Christian Bale",
    players_count: 2,
    players_limit: 3,
    status: "open",
  },
  {
    id: 9,
    price: 10,
    currency: "TON",
    owner_name: "Christian Bale",
    players_count: 2,
    players_limit: 3,
    status: "private",
  },
  {
    id: 10,
    price: null,
    currency: null,
    owner_name: "Christian Bale",
    players_count: 2,
    players_limit: 3,
    status: "private",
  },
  {
    id: 11,
    price: 5,
    currency: "DUR",
    owner_name: "Christian Bale",
    players_count: 2,
    players_limit: 3,
    status: "private",
  },
];

export default rArr;
